### ISSUE TITLE
Milestone 2 - A6 Feedback

### ISSUE THREAD

**Issue by sgvillal** [tjke/C121#2]
# **Scott 2**

- I like the character and how it shows the physical toll that your activities can have on you

- we think charts such as a pie chart would be a good addition so you can how your 24 are spent in % wise

- Cool that it categorizes by location what youre doing but idk if that will be hard to categorize, a lot to do manually for the user?

- I think it would be cool if it let you see daily weekly and yearly so effects can more clearly be seen.

- I think that its a good idea, just try to incorporate the map more, also try to think about how the app will detect whether the user is studying or running or eating, etc

# **Michael 2**

- I think that its a good idea because I often have to open up a bunch of apps to check out the prices

- With surge prices its important too

- It might be helpful to check out uberestimates.com for inspiration into how to code this

- Would be cool to do future check, where takes previous data for that time and date of the week, what might be the prices of each of the transportation

**Comment by kandarpksk** [comment]
@sgvillal Please move this to the original thread and close this issue.
